### PR TITLE
Update to galenframework V2.1.3

### PR DESCRIPTION
**Pull request by michaseel**
Use the new Version of the galenframework

### CODE REVIEW

**Comment by mjurczyk** [comment]
@michaseel some problems here, will have to refactor tests before this can be merged.

**Comment by michaseel** [comment]
I updated the galen spec language file and fixed the error report handler.
On my machine `npm test`runs successfull. Dont know why TravisBuild fails

**Comment by michaseel** [comment]
seems to be a problem with firefox on Travis.
See http://stackoverflow.com/questions/24653127/selenium-error-no-display-specified

**Comment by michaseel** [comment]
Ok, this was a travis Error. See: https://docs.travis-ci.com/user/gui-and-headless-browsers/

**Pull request merged**
